time_limit = 2.0

[[generators]]
language_name = "C++"
path = "gen.cpp"

[[languages]]
language_name = "C++"
target_ext = ".cpp"
compile = ["g++", "-O2", "-std=gnu++11", "-o", "$OUT", "$IN"]
run = ["$OUT"]

[[solutions]]
path = "sol.cpp"
language_name = "C++"
is_reference_solution = true

[[solutions]]
path = "wa.cpp"
language_name = "C++"
expected_verdict = "wa"

[[solutions]]
path = "re.cpp"
language_name = "C++"
expected_verdict = "re"
