name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -D warnings

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --locked
    - name: Run clippy
      run: cargo clippy --all-targets --locked
    - name: Check formatting
      run: cargo fmt -- --check
